# Generated by Django 3.2.8 on 2021-10-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Название')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='audio_content', serialize=False, to='content_app.content')),
                ('bpm', models.PositiveSmallIntegerField(verbose_name='Кол-во bpm')),
            ],
            options={
                'verbose_name': 'Аудиофайл',
                'verbose_name_plural': 'Аудиофайлы',
            },
            bases=('content_app.content', models.Model),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='text_content', serialize=False, to='content_app.content')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
            bases=('content_app.content', models.Model),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='video_content', serialize=False, to='content_app.content')),
                ('video_link', models.CharField(max_length=2048, verbose_name='Ссылка на видео')),
                ('sub_link', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на субтитры')),
            ],
            options={
                'verbose_name': 'Видеофайл',
                'verbose_name_plural': 'Видеофайлы',
            },
            bases=('content_app.content', models.Model),
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content_app.page', verbose_name='Страница'),
        ),
    ]
